(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 24,
	color: "#000000",
	manifest: []
};



// symbols:



(lib.矩形 = function() {
	this.initialize();

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#FF0E0E","#FFC25B","#FF0000"],[0,0.565,1],-50.5,0,50.5,0).s().p("An3TYMAAAgmvIPvAAMAAAAmvg");
	this.shape.setTransform(50.5,124);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,101,248);


// stage content:
(lib._07文字扫光效果 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 遮罩 (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AlDCWIAgg2QArAQA8AYIA/g+Ii9AAIAAg2IAQgtIg9AAIAAg5IBPAAIAMgsIhDAAIAAg4IBSAAIAOg8IBKAAIgOA8ICaAAIAAA4IipAAIgMAsIDHAAIAAA5IjZAAIgOArIDRAAIAAA0IhcBeIA+AZIgjA7QhZgqiMg4gA3xDDQA4hFgDibIAAidIC1AAIgRgsIBPgRIAXA9ICpAAIAABCIlsAAIAABkQAACxhDBbQgBgDg4gygAVnD2IAAgYIjaAAIAAAYIhEAAIAAinIguAIQgLgfgOgaQBogNBIgRQgagPgYgWQgeAVgkAQQgSgYgTgVQBVgjA1g4IBNAAIgRAUIC7AAIAAgfIlAAAIAAA/IhEAAIAAh3IDBAAIgPgkIBVgIIAQAsICxAAIAAB3Ig8AAIAAAPQglAog3AdQBIAPBkAHIgZA9IgugHIAACqgASNCmIDaAAIAAglIjaAAgARtBHIEpAAQhcgQg/gWQg8AVhSARgAT8gVQAqgSAigaIiXAAQAhAaAqASgAm9D1IAAjmQgTAjgWAhQgGgngLg0QA+hlAkiKIBCASQgTA7gXA3IAAFogAvlDGQBPhKgDicIAAjMIBBAAIAACLIA3gNQASA9ARBMIg6AQQgPhMgRg7IAABAQAAB9gdA+QgcA+gbAYQgWgUgjgbgAKzD1IAAjJIgcgeIABAXIgiAKIAACCQAAAmgRAOQgSAOhBgBIgMhBIAlAAQAOAAAAgVIAAhbIgwANIgFhJIA1gJIAAhWIgwAAIAAg+IAwAAIAAhZIA9AAIAABZIAmAAIAAA+IgmAAIAABHIAigJIgBAWQA3gXAqggIhYAAIAAgwIBAAAQgSgSgWgTIAYgWIghABIgJg0QDOgFBhgIIAJAyIgtADIAiAbIguArIBJAAIAAAwIhiAAQAtAkA+AQQgJALgXAiIAADPIg8AAIAAgUIisAAIAAAWgANjCwIA4AAIAAgeIg4AAgALvCwIA3AAIAAgeIg3AAgANjBlIA4AAIAAgfIg4AAgALvBlIA3AAIAAgfIg3AAgAOxAXQgugagggqIAAA4Ig9AAIAAg4QgmApgrAbIDcAAIAAAAgANjiuIAABBIAvAAIgbgZIAugsgALoipQAWATATARIgaAYIAvAAIAAg+gAF7D1IAAgXIj4AAIAAAXIhDAAIAAjeIgRAHQgSgbgTgSQBMgeASgjIhaAAIAAgwIAfAAQgPgYgOgSQAbgaAbgzIBAAAQgIATgJAQICLAAIAAAxIhFAAQgBATgDAQIBYAAIAAAwIhNAAIBHAwIghAjIDWAAIAADygACDCqID4AAIAAggIj4AAgACDBZID4AAIAAgjIj4AAgABmADIByAAQgggcgbgXQgSAeglAVgAA4iAIA/AAQACgQABgTIgkAAQgOAUgQAPgApiDuIAAjYIg2AQQgPg6gWhFIAAE+IhBAAIAAnQIBBAAIAACHIAygPQATA1AWBMIAAj8IBAAAIAAHcgAv3AbQAVhAAShOIA2AOQgTBZgSA8gAEXgYIAAi6IDHAAIAAC6gAFVhMIBLAAIAAhRIhLAAg");
	mask.setTransform(275,194.3);

	// 光效
	this.instance = new lib.矩形("synched",0);
	this.instance.setTransform(63.5,201,1,1,0,0,0,50.5,124);

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:486.5},14).to({x:63.5},15).wait(1));

	// 背景
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AlDCWIAgg2QArAQA8AYIA/g+Ii9AAIAAg2IAQgtIg9AAIAAg5IBPAAIAMgsIhDAAIAAg4IBSAAIAOg8IBKAAIgOA8ICaAAIAAA4IipAAIgMAsIDHAAIAAA5IjZAAIgOArIDRAAIAAA0IhcBeIA+AZIgjA7QhZgqiMg4gA3xDDQA4hFgDibIAAidIC1AAIgRgsIBPgRIAXA9ICpAAIAABCIlsAAIAABkQAACxhDBbQgBgDg4gygAVnD2IAAgYIjaAAIAAAYIhEAAIAAinIguAIQgLgfgOgaQBogNBIgRQgagPgYgWQgeAVgkAQQgSgYgTgVQBVgjA1g4IBNAAIgRAUIC7AAIAAgfIlAAAIAAA/IhEAAIAAh3IDBAAIgPgkIBVgIIAQAsICxAAIAAB3Ig8AAIAAAPQglAog3AdQBIAPBkAHIgZA9IgugHIAACqgASNCmIDaAAIAAglIjaAAgARtBHIEpAAQhcgQg/gWQg8AVhSARgAT8gVQAqgSAigaIiXAAQAhAaAqASgAm9D1IAAjmQgTAjgWAhQgGgngLg0QA+hlAkiKIBCASQgTA7gXA3IAAFogAvlDGQBPhKgDicIAAjMIBBAAIAACLIA3gNQASA9ARBMIg6AQQgPhMgRg7IAABAQAAB9gdA+QgcA+gbAYQgWgUgjgbgAKzD1IAAjJIgcgeIABAXIgiAKIAACCQAAAmgRAOQgSAOhBgBIgMhBIAlAAQAOAAAAgVIAAhbIgwANIgFhJIA1gJIAAhWIgwAAIAAg+IAwAAIAAhZIA9AAIAABZIAmAAIAAA+IgmAAIAABHIAigJIgBAWQA3gXAqggIhYAAIAAgwIBAAAQgSgSgWgTIAYgWIghABIgJg0QDOgFBhgIIAJAyIgtADIAiAbIguArIBJAAIAAAwIhiAAQAtAkA+AQQgJALgXAiIAADPIg8AAIAAgUIisAAIAAAWgANjCwIA4AAIAAgeIg4AAgALvCwIA3AAIAAgeIg3AAgANjBlIA4AAIAAgfIg4AAgALvBlIA3AAIAAgfIg3AAgAOxAXQgugagggqIAAA4Ig9AAIAAg4QgmApgrAbIDcAAIAAAAgANjiuIAABBIAvAAIgbgZIAugsgALoipQAWATATARIgaAYIAvAAIAAg+gAF7D1IAAgXIj4AAIAAAXIhDAAIAAjeIgRAHQgSgbgTgSQBMgeASgjIhaAAIAAgwIAfAAQgPgYgOgSQAbgaAbgzIBAAAQgIATgJAQICLAAIAAAxIhFAAQgBATgDAQIBYAAIAAAwIhNAAIBHAwIghAjIDWAAIAADygACDCqID4AAIAAggIj4AAgACDBZID4AAIAAgjIj4AAgABmADIByAAQgggcgbgXQgSAeglAVgAA4iAIA/AAQACgQABgTIgkAAQgOAUgQAPgApiDuIAAjYIg2AQQgPg6gWhFIAAE+IhBAAIAAnQIBBAAIAACHIAygPQATA1AWBMIAAj8IBAAAIAAHcgAv3AbQAVhAAShOIA2AOQgTBZgSA8gAEXgYIAAi6IDHAAIAAC6gAFVhMIBLAAIAAhRIhLAAg");
	this.shape.setTransform(275,194.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(30));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(397.8,369.4,304.5,49.8);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;