(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 550,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



// stage content:
(lib._02补间形状失效 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// 图层 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#0033FF").s().p("AlnFoQiViVgBjTQABjSCViVQCViVDSgBQDTABCVCVQCVCVAADSQAADTiVCVQiVCVjTAAQjSAAiViVg");
	this.shape.setTransform(249,186);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#0033FF").s().p("AAXIkIgXAAIgWAAIgXAAQjUAAiViVQiViVAAjTIAAgUIAAgTIAAgSIAAgTQAAjUCViVQBHhIBWglQBdgpBuAAIAXABIAXgBIAWABIAXgBQBtABBcAnQBYAkBJBKQCVCVAADUIAAATIAAASIAAATIAAAUQAADTiVCVQiVCVjUAAIgXAAg");
	this.shape_1.setTransform(249.1,187);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#0033FF").s().p("AAtJJQgXACgWAAQgYAAgWgBQgWABgYAAQjTAAiWiVQiViVAAjUIABgmIgBgnIABglIgBgnQAAjUCViVQBIhIBWglQBdgoBtAAQAYAAAWABQAXgBAXAAQAWAAAXACQAYgCAYAAQBtAABcAnQBXAlBJBJQCWCVAADUIgCAnIACAlIgCAnIACAmQAADUiWCVQiVCVjTAAQgYAAgYgCg");
	this.shape_2.setTransform(249.2,187.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#0033FF").s().p("ABEJuQgiAFgjAAQgjAAgigFQghAFgjAAQjUAAiViWQiViVgBjTQAAgeAEgdQgEgcAAgeQAAgcAEgdQgEgcAAgeQABjUCViVQBHhIBWglQBdgpBuAAQAjABAiAEQAhgEAjgBQAjABAjAEQAjgEAkgBQBtABBcAnQBXAkBJBKQCWCVAADUQAAAegEAcQAEAdAAAcQAAAegEAcQAEAdAAAeQAADTiWCVQiVCWjTAAQglAAgjgFg");
	this.shape_3.setTransform(249.3,188.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#0033FF").s().p("ABbKRQguAIgvAAQgvAAgtgHQgsAHgvAAQjUAAiViVQiViVgBjUQABgnAFgmQgFgmgBgnQABgnAFgmQgFgmgBgoQABjUCViVQBHhIBWglQBdgoBuAAQAvAAAtAHQAsgHAvAAQAwAAAuAIQAtgIAxAAQBtAABdAnQBXAlBJBJQCVCVAADUQAAAogFAmQAFAmAAAnQABAngGAmQAGAmgBAnQAADUiVCVQiVCVjUAAQgxAAgugIg");
	this.shape_4.setTransform(249.4,189.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#0033FF").s().p("AByKzQg5ANg8AAQg8AAg2gMQg3AMg8AAQjUAAiViVQiViVAAjUQAAgyAIguQgIgvAAgyQAAgxAIgvQgIgvAAgzQAAjUCViVQBIhIBWglQBdgoBtAAQA8AAA4AMQA2gMA7AAQA9AAA5ANQA5gNA9AAQBuAABcAnQBXAlBJBJQCVCVAADUQAAAzgIAvQAIAvAAAxQAAAygIAvQAIAuAAAyQAADUiVCVQiVCVjUAAQg+AAg5gNg");
	this.shape_5.setTransform(249.4,190.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#0033FF").s().p("ACJLUQhDAThKAAQhIAAhBgRQhBARhJAAQjTAAiWiVQiViVAAjUQAAg8ANg4QgNg3AAg8QAAg8ANg4QgNg5AAg9QAAjUCViVQBIhIBWglQBdgoBtAAQBJAABBARQBBgRBIAAQBKAABDATQBEgTBLAAQBtAABcAnQBXAlBJBJQCWCVAADUQAAA9gNA5QANA4AAA8QAAA8gNA3QANA4AAA8QAADUiWCVQiVCVjTAAQhMAAhDgTg");
	this.shape_6.setTransform(249.5,191.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#0033FF").s().p("ACgL0QhOAahWAAQhWAAhLgYQhLAYhWAAQjTAAiViVQiWiVAAjUQABhHAQhAQgQhAgBhHQAAhHAShBQgShBAAhIQAAjUCWiVQBHhIBWglQBdgoBuAAQBVAABMAYQBLgYBVAAQBXAABOAaQBNgaBZAAQBtAABcAnQBXAlBJBJQCVCVAADUQAABIgRBBQARBBAABHQABBHgSBAQASBAgBBHQAADUiVCVQiVCVjTAAQhZAAhOgag");
	this.shape_7.setTransform(249.6,192.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#0033FF").s().p("AC3MSQhYAjhkAAQhjAAhVggQhVAghiAAQjUAAiViVQiViVAAjUQAAhSAWhIQgWhJAAhSQAAhRAXhKQgXhKAAhTQAAjUCViVQBHhIBXglQBdgoBtAAQBkAABVAgQBUggBiAAQBmAABXAjQBYgjBmAAQBtAABcAnQBXAlBJBJQCVCVAADUQAABTgXBKQAXBKAABRQAABSgWBJQAWBIAABSQAADUiVCVQiVCVjUAAQhmAAhYgjg");
	this.shape_8.setTransform(249.7,193.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#0033FF").s().p("ADOMvQhiAthyAAQhwAAhfgqQheAqhwAAQjUAAiViVQiViVAAjUQAAhdAdhRQgdhQAAhdQAAhdAehSQgehTAAheQAAjUCViVQBIhIBWglQBdgoBtAAQBuAABcAnIAGADIADgCQBdgoBtAAQBsAABcAnIANAGIALgFQBdgoBuAAQBtAABcAnQBXAlBJBJQCVCVAADUQAABegeBTQAeBSAABdQAABdgdBQQAdBRAABdQAADUiVCVQiVCVjUAAQh0AAhigtg");
	this.shape_9.setTransform(249.8,194.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#0033FF").s().p("ADlNKQhrA5iBAAQh+AAhng1QhoA1h+AAQjTAAiWiWQiUiVAAjTQAAhoAkhZQgkhZAAhoQgBhoAmhbQgmhaABhqQAAjUCUiVQBIhIBWglQBdgoBtAAQBuAABcAnIAdANIAagMQBdgoBtAAQBsAABcAnQATAIASAKQARgJARgIQBdgoBuAAQBuAABbAnQBXAlBJBJQCWCVAADUQAABqgmBaQAmBbAABoQAABoglBZQAlBZAABoQAADTiWCVQiVCWjUAAQiCAAhrg5g");
	this.shape_10.setTransform(249.9,195.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#0033FF").s().p("AD8NkQh0BGiQAAQiLAAhxhBQhxBBiLAAQjUAAiViVQiViVAAjUQAAhzAshhQgshhAAh0QAAh0AuhiQguhiAAh2QAAjUCViVQBHhIBXglQBdgoBtAAQBuAABcAnQAaALAZAPQAYgOAZgLQBdgoBuAAQBrAABcAnQAfAOAeARQAcgRAegNQBdgoBuAAQBuAABbAnQBXAlBJBJQCVCVAADUQAAB2guBiQAuBiAAB0QAAB0gsBhQAsBhAABzQAADUiVCVQiVCVjUAAQiRAAh0hGg");
	this.shape_11.setTransform(249.9,196.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#0033FF").s().p("AESN7Qh8BWifAAQiaAAh5hQQh5BQiaAAQjUAAiViVQiViVAAjUQAAh/A2hpQg2hoAAiAQAAh/A4hqQg4hqAAiCQAAjUCViVQBIhIBWglQBdgoBtAAQBuAABcAnQAmAQAkAYQAjgXAlgQQBdgoBuAAQBrAABcAnQAsATAoAcQAogcArgSQBdgoBtAAQBuAABcAnQBXAlBJBJQCVCVAADUQAACCg4BqQA4BqAAB/QAACAg2BoQA2BpAAB/QAADUiVCVQiVCVjUAAQigAAh+hWg");
	this.shape_12.setTransform(250,197.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#0033FF").s().p("AEpOQQiFBoiuAAQipAAiBhfQiBBfipAAQjTAAiWiWQiViUAAjUQAAiLBBhwQhBhwAAiLQAAiMBDhyQhDhxAAiOQAAjTCViWQBIhIBWglQBdgoBtAAQBuAABcAoQAzAVAuAiQAtghAygWQBdgoBuAAQBsAABbAoQA5AYAzAnQAygnA5gYQBdgoBtAAQBuAABcAoQBXAkBIBJQCWCWAADTQAACOhEBxQBEByAACMQAACLhBBwQBBBwAACLQAADUiWCUQiVCWjTAAQiwAAiGhog");
	this.shape_13.setTransform(250.1,198.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#0033FF").s().p("AFAOjQiMB8i+AAQi5AAiJhxQiIBxi5AAQjTAAiWiWQiUiVAAjTQgBiXBMh3QhMh4ABiXQAAiYBPh5QhPh5AAiaQAAjTCUiWQBIhHBXglQBdgpBtAAQBuABBcAnQA/AbA4AuQA3guA/gaQBegpBtAAQBsABBcAnQBGAeA9A1QA8g1BGgdQBegpBtAAQBuABBbAnQBXAlBJBIQCVCWAADTQAACahPB5QBPB5AACYQAACXhMB4QBMB3AACXQAADTiVCVQiVCWjTAAQjBAAiNh8g");
	this.shape_14.setTransform(250.2,199.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0033FF").s().p("AFXO0QiUCSjOAAQjIAAiQiFQiQCFjIAAQjUAAiViVQiViVAAjUQAAijBZh/QhZh+AAikQAAikBciAQhciAAAinQAAjTCViWQBIhIBWglQBdgoBtAAQBuAABcAoQBNAgBCA9QBBg8BMghQBdgoBtAAQBsAABcAoQBUAjBHBGQBHhFBTgkQBdgoBuAAQBuAABcAoQBWAkBJBJQCVCWAADTQAACnhdCAQBdCAAACkQAACkhZB+QBZB/AACjQAADUiVCVQiVCVjUAAQjQAAiViSg");
	this.shape_15.setTransform(250.3,200.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#0033FF").s().p("AGCPYIgUgVIgUAVQiVCVjRAAQjTAAiWiVIgGgHIgGAHQiVCVjUAAQjUAAiViVQiViVAAjUQAAiwBniFQhniFAAiwQAAiyBsiHQhsiGAAi0QAAjTCViWQBIhHBWglQBegpBtAAQBuABBbAnQBXAlBJBIIAGAGIAGgGQBIhHBWglQBdgpBtAAQBsABBdAnQBWAlBIBIIAUAVIAUgVQBIhHBWglQBdgpBuAAQBuABBbAnQBXAlBJBIQCVCWAADTQAAC0hsCGQBsCHAACyQAACwhnCFQBnCFAACwQAADUiVCVQiVCVjUAAQjTAAiWiVg");
	this.shape_16.setTransform(250.4,201.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#0033FF").s().p("AGxP/QgYgYgUgZQgUAZgYAYQiVCVjRAAQjTAAiWiVQgPgQgOgQQgOAQgPAQQiVCVjTAAQjUAAiWiVQiViVABjUQgBi9B3iLQh3iMABi8QAAjAB8iNQh8iNAAjBQgBjUCViVQBIhIBWglQBegoBtAAQBuABBcAnQBXAlBIBIQAPAPAOAQQAOgQAPgPQBIhIBWglQBdgoBtAAQBtABBcAnQBWAlBIBIQAYAYAUAZQAUgZAYgYQBIhIBWglQBdgoBuAAQBtABBcAnQBXAlBIBIQCWCVAADUQAADBh9CNQB9CNAADAQAAC8h4CMQB4CLAAC9QAADUiWCVQiVCVjTAAQjUAAiViVg");
	this.shape_17.setTransform(250.5,202.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#0033FF").s().p("AHfQlQgmgmgdgsQgdAsgnAmQiVCWjRAAQjTAAiWiWQgdgcgXgfQgXAfgdAcQiVCWjUAAQjTAAiWiWQiViVABjTQgBjKCJiSQiJiRABjKQgBjNCPiTQiPiTABjPQgBjTCViWQBJhIBWglQBdgoBtAAQBvAABbAoQBXAlBIBIQAdAdAXAfQAXgfAdgdQBIhIBWglQBdgoBtAAQBtAABcAoQBWAlBIBIQAnAnAdArQAdgrAmgnQBIhIBXglQBdgoBtAAQBuAABcAoQBXAlBIBIQCVCWAADTQAADPiOCTQCOCTAADNQAADKiICRQCICSAADKQAADTiVCVQiVCWjUAAQjTAAiWiWg");
	this.shape_18.setTransform(250.6,203.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#0033FF").s().p("AIORNQg4g5gjhBQgjBBg4A5QiVCVjSAAQjTAAiWiVQgsgsgegyQggAygsAsQiVCVjTAAQjUAAiViVQiViVAAjUQAAjTCViWIAGgGIgGgHQiViVAAjTQAAjSCViVIANgNIgNgNQiViVAAjTQAAjUCViVQBIhIBWglQBdgoBuAAQBuABBcAnQBWAlBIBIQAsAsAgAyQAegyAsgsQBIhIBWglQBdgoBuAAQBsABBcAnQBWAlBJBIQA4A4AjBCQAjhCA4g4QBIhIBWglQBdgoBuAAQBuABBcAnQBWAlBJBIQCVCVAADUQAADTiVCVIgOANIAOANQCVCVAADSQAADTiVCVIgHAHIAHAGQCVCWAADTQAADUiVCVQiVCVjUAAQjTAAiWiVg");
	this.shape_19.setTransform(250.6,204.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#0033FF").s().p("AI9RzQhOhNglhfQglBfhOBNQiVCWjSAAQjTAAiWiWQg9g9gkhIQglBIg9A9QiVCWjUAAQjTAAiWiWQiViVAAjTQAAjUCViVIAbgaIgbgZQiViVAAjUQAAjRCViWQARgRASgPQgSgPgRgRQiViVAAjUQAAjTCViWQBIhIBWglQBdgoBuAAQBuAABcAoQBWAlBJBIQA9A+AlBIQAkhIA9g+QBIhIBWglQBdgoBuAAQBsAABcAoQBWAlBJBIQBOBOAlBfQAlhfBOhOQBHhIBXglQBdgoBtAAQBvAABbAoQBXAlBIBIQCWCWAADTQAADUiWCVQgRARgSAPQASAPARARQCWCWAADRQAADUiWCVIgbAZIAbAaQCWCVAADUQAADTiWCVQiVCWjTAAQjUAAiViWg");
	this.shape_20.setTransform(250.7,205.3);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#0033FF").s().p("AJsSaQhuhtgdiQQgdCQhuBtQiVCWjRAAQjUAAiViWQhUhUglhnQglBnhUBUQiVCWjTAAQjUAAiViWQiViVgBjTQABjUCViVQAYgZAagUQgagUgYgZQiViVgBjTQABjSCViVQAcgdAfgXQgfgXgcgdQiViVgBjUQABjTCViWQBIhIBVglQBegoBtAAQBuABBcAnQBXAlBIBIQBUBUAlBoQAlhoBUhUQBIhIBVglQBegoBtAAQBsABBcAnQBWAlBJBIQBuBuAdCQQAdiQBuhuQBIhIBVglQBegoBtAAQBuABBcAnQBWAlBJBIQCVCWAADTQAADUiVCVQgdAdgfAXQAfAXAdAdQCVCVAADSQAADTiVCVQgYAZgbAUQAbAUAYAZQCVCVAADUQAADTiVCVQiVCWjTAAQjUAAiViWg");
	this.shape_21.setTransform(250.8,206.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#0033FF").s().p("AKaTBQiViVAAjTQAAjUCViVQAlglAogbQgogcglgkQiViVAAjUQAAjRCViWQAqgpAvgeQgvgfgqgpQiViVAAjUQAAjTCViWQBIhHBXglQBdgpBtAAQBvABBbAnQBXAlBIBIQCVCWAADTQAADUiVCVQgqAqgvAeQAvAeAqApQCVCWAADRQAADUiVCVQglAkgoAcQAoAbAlAlQCVCVAADUQAADTiVCVQiVCWjUAAQjTAAiWiWgAl6TBQh5h4gXihQgXChh5B4QiVCWjTAAQjUAAiViWQiViVAAjTQAAjUCViVQAkglApgbQgpgcgkgkQiViVAAjUQAAjRCViWQApgpAvgeQgvgfgpgpQiViVAAjUQAAjTCViWQBIhHBWglQBdgpBuAAQBuABBcAnQBWAlBIBIQB5B5AXChQAXihB5h5QBIhHBWglQBdgpBuAAQBsABBcAnQBWAlBIBIQCWCWAADTQAADUiWCVQgpAqgvAeQAvAeApApQCWCWAADRQAADUiWCVQgkAkgoAcQAoAbAkAlQCWCVAADUQAADTiWCVQiVCWjRAAQjUAAiViWg");
	this.shape_22.setTransform(250.9,207.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#0033FF").s().p("ALJToQiViVAAjTQAAjUCViVQAygyA6giQg6ghgygyQiViVAAjUQAAjRCViWQA4g4BBgjQhBgjg4g4QiViVAAjUQAAjTCViWQBIhIBWglQBdgoBuAAQBuABBcAnQBWAlBJBIQCVCWAADTQAADUiVCVQg5A4hBAjQBBAjA5A4QCVCWAADRQAADUiVCVQgyAyg5AhQA5AhAyAzQCVCVAADUQAADTiVCVQiVCWjUAAQjTAAiWiWgAl7ToQiViVAAjTQAAjUCViVQAygyA5giQg5ghgygyQiViVAAjUQAAjRCViWQA4g4BBgjQhBgjg4g4QiViVAAjUQAAjTCViWQBIhIBXglQBdgoBtAAQBsABBcAnQBXAlBHBIQCWCWAADTQAADUiWCVQg4A4hBAjQBBAjA4A4QCWCWAADRQAADUiWCVQgxAyg6AhQA6AhAxAzQCWCVAADUQAADTiWCVQiVCWjRAAQjTAAiWiWgA2aToQiViVAAjTQAAjUCViVQAygyA6giQg6ghgygyQiViVAAjUQAAjRCViWQA4g4BBgjQhBgjg4g4QiViVAAjUQAAjTCViWQBIhIBWglQBdgoBuAAQBvABBbAnQBWAlBJBIQCVCWAADTQAADUiVCVQg5A4hBAjQBBAjA5A4QCVCWAADRQAADUiVCVQgyAyg6AhQA6AhAyAzQCVCVAADUQAADTiVCVQiVCWjUAAQjTAAiWiWg");
	this.shape_23.setTransform(251,208.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#0033FF").s().p("AL4UPQiWiVAAjTQAAjUCWiVQBBhCBPglQhOglhChCQiWiVAAjTQAAjSCWiVQBIhIBWglIAEgCQhZglhJhKQiWiVAAjUQAAjTCWiWQBIhIBWglQBdgoBtAAQBvABBbAnQBXAlBIBIQCWCWAADTQAADUiWCVQhKBKhZAlIAEACQBXAlBIBIQCWCVAADSQAADTiWCVQhCBChOAlQBOAlBCBCQCWCVAADUQAADTiWCVQiVCWjUAAQjTAAiViWgAl8UPQiViVAAjTQAAjUCViVQBChCBOglQhOglhChCQiViVAAjTQAAjSCViVQBIhIBXglIAEgCQhZglhKhKQiViVAAjUQAAjTCViWQBIhIBXglQBdgoBtAAQBsABBcAnQBXAlBHBIQCWCWAADTQAADUiWCVQhJBKhZAlIAEACQBXAlBHBIQCWCVAADSQAADTiWCVQhBBChOAlQBOAlBBBCQCWCVAADUQAADTiWCVQiVCWjRAAQjTAAiWiWgA3IUPQiViVgBjTQABjUCViVQBBhCBPglQhPglhBhCQiViVgBjTQABjSCViVQBHhIBWglIAFgCQhZgmhJhJQiViVgBjUQABjTCViWQBHhIBWglQBdgoBuAAQBvABBbAnQBXAlBIBIQCWCWAADTQAADUiWCVQhKBKhYAlIADACQBXAlBIBIQCWCVAADSQAADTiWCVQhCBChOAlQBOAlBCBCQCWCVAADUQAADTiWCVQiVCWjTAAQjUAAiViWg");
	this.shape_24.setTransform(251.1,209.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#0033FF").s().p("AMmU2QiViVAAjTQAAjUCViVQBIhIBXglIAhgNQhqglhWhVQiViVAAjUQAAjRCViWQBIhIBXglQAegNAfgIQh7gihhhhQiViVAAjUQAAjTCViWQBIhHBXglQBdgpBtAAQBvABBcAnQBWAlBIBIQCVCWAADTQAADUiVCVQhhBhh7AiQAgAIAeANQBWAlBIBIQCVCWAADRQAADUiVCVQhWBVhqAlIAiANQBWAlBIBIQCVCVAADUQAADTiVCVQiVCWjUAAQjTAAiWiWgAl9U2QiViVAAjTQAAjUCViVQBIhIBXglIAhgNQhqglhWhVQiViVAAjUQAAjRCViWQBIhIBXglQAegNAfgIQh7gihhhhQiViVAAjUQAAjTCViWQBIhHBXglQBdgpBtAAQBtABBbAnQBXAlBIBIQCVCWAADTQAADUiVCVQhhBhh7AiQAgAIAdANQBXAlBIBIQCVCWAADRQAADUiVCVQhWBVhqAlIAhANQBXAlBIBIQCVCVAADUQAADTiVCVQiVCWjSAAQjTAAiWiWgA33U2QiViVAAjTQAAjUCViVQBIhIBWglIAhgNQhqglhVhVQiViVAAjUQAAjRCViWQBIhIBWglQAegNAfgIQh6gihhhhQiViVAAjUQAAjTCViWQBIhHBWglQBdgpBuAAQBuABBcAnQBWAlBIBIQCWCWAADTQAADUiWCVQhgBhh7AiQAfAIAeANQBWAlBIBIQCWCWAADRQAADUiWCVQhVBVhqAlIAhANQBWAlBIBIQCWCVAADUQAADTiWCVQiVCWjTAAQjUAAiViWg");
	this.shape_25.setTransform(251.1,210.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#0033FF").s().p("ANVVdQiViVAAjUQAAjTCViWQBIhHBWglQA0gXA4gKQiXgahzhzQiViVAAjTQAAjSCViWQBIhHBWgmQBdgoBuABQBvAABbAnQBWAmBJBHQCVCWAADSQAADTiVCVQhzBziYAaQA5AKAzAXQBWAlBJBHQCVCWAADTQAADUiVCVQiVCWjUAAQjTAAiWiWgAl+VdQiViVAAjUQAAjTCViWQBIhHBXglQAzgXA5gKQiYgahzhzQiViVAAjTQAAjSCViWQBIhHBXgmQBdgoBtABQBtAABbAnQBXAmBIBHQCVCWAADSQAADTiVCVQhzBziYAaQA5AKAzAXQBXAlBIBHQCVCWAADTQAADUiVCVQiVCWjSAAQjTAAiWiWgA4mVdQiViVAAjUQAAjTCViWQBIhHBWglQA0gXA4gKQiXgahzhzQiViVAAjTQAAjSCViWQBIhHBWgmQBdgoBuABQBvAABbAnQBWAmBIBHQCWCWAADSQAADTiWCVQhyBziYAaQA5AKAzAXQBWAlBIBHQCWCWAADTQAADUiWCVQiVCWjTAAQjUAAiViWgANVqLQiViVAAjUQAAjTCViVQBIhIBWglQBdgpBuAAQBvABBbAoQBWAlBJBIQCVCVAADTQAADUiVCVQiVCWjUAAQjTAAiWiWgAl+qLQiViVAAjUQAAjTCViVQBIhIBXglQBdgpBtAAQBtABBbAoQBXAlBIBIQCVCVAADTQAADUiVCVQiVCWjSAAQjTAAiWiWgA4mqLQiViVAAjUQAAjTCViVQBIhIBWglQBdgpBuAAQBvABBbAoQBWAlBIBIQCWCVAADTQAADUiWCVQiVCWjTAAQjUAAiViWg");
	this.shape_26.setTransform(251.2,211.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#0033FF").s().p("AOEWEQiViVAAjTQAAjUCViVQBIhIBXglQBdgoBtAAQBvAABbAnQBXAlBHBJQCWCVAADUQAADTiWCVQiUCWjUAAQjUAAiViWgAl+WEQiViVgBjTQABjUCViVQBHhIBXglQBdgoBuAAQBsAABcAnQBWAlBIBJQCVCVAADUQAADTiVCVQiVCWjRAAQjUAAiViWgA5VWEQiViVAAjTQAAjUCViVQBIhIBXglQBcgoBuAAQBvAABcAnQBWAlBHBJQCWCVAADUQAADTiWCVQiVCWjTAAQjTAAiWiWgAOEFxQiViVAAjTQAAjSCViVQBIhIBXglQBdgoBtAAQBvAABbAoQBXAlBHBIQCWCVAADSQAADTiWCVQiUCWjUAAQjUAAiViWgAl+FxQiViVgBjTQABjSCViVQBHhIBXglQBdgoBuAAQBsAABcAoQBWAlBIBIQCVCVAADSQAADTiVCVQiVCWjRAAQjUAAiViWgA5VFxQiViVAAjTQAAjSCViVQBIhIBXglQBcgoBuAAQBvAABcAoQBWAlBHBIQCWCVAADSQAADTiWCVQiVCWjTAAQjTAAiWiWgAOEqyQiViVAAjUQAAjTCViWQBIhIBXglQBdgoBtAAQBvABBbAnQBXAlBHBIQCWCWAADTQAADUiWCVQiUCVjUAAQjUAAiViVgAl+qyQiViVgBjUQABjTCViWQBHhIBXglQBdgoBuAAQBsABBcAnQBWAlBIBIQCVCWAADTQAADUiVCVQiVCVjRAAQjUAAiViVgA5VqyQiViVAAjUQAAjTCViWQBIhIBXglQBcgoBuAAQBvABBcAnQBWAlBHBIQCWCWAADTQAADUiWCVQiVCVjTAAQjTAAiWiVg");
	this.shape_27.setTransform(251.3,212.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#0033FF").s().p("AOzWrQiWiVAAjUQAAjTCWiWQBHhHBXgmQBdgoBuABQBvAABbAnQBWAmBIBHQCVCWAADTQAADUiVCVQiVCVjTAAQjUAAiViVgAl/WrQiViVAAjUQAAjTCViWQBHhHBXgmQBdgoBuABQBsAABcAnQBWAmBIBHQCVCWAADTQAADUiVCVQiVCVjRAAQjUAAiViVgA6DWrQiWiVAAjUQAAjTCWiWQBIhHBWgmQBdgoBtABQBvAABcAnQBWAmBIBHQCWCWAADTQAADUiWCVQiVCVjUAAQjTAAiViVgAOzFxQiWiVAAjTQAAjSCWiVQBHhIBXglQBdgoBuAAQBvABBbAnQBWAlBIBIQCVCVAADSQAADTiVCVQiVCWjTAAQjUAAiViWgAl/FxQiViVAAjTQAAjSCViVQBHhIBXglQBdgoBuAAQBsABBcAnQBWAlBIBIQCVCVAADSQAADTiVCVQiVCWjRAAQjUAAiViWgA6DFxQiWiVAAjTQAAjSCWiVQBIhIBWglQBdgoBtAAQBvABBcAnQBWAlBIBIQCWCVAADSQAADTiWCVQiVCWjUAAQjTAAiViWgAOzrZQiWiVAAjUQAAjTCWiVQBHhIBXglQBdgpBuAAQBvABBbAoQBWAlBIBIQCVCVAADTQAADUiVCVQiVCWjTAAQjUAAiViWgAl/rZQiViVAAjUQAAjTCViVQBHhIBXglQBdgpBuAAQBsABBcAoQBWAlBIBIQCVCVAADTQAADUiVCVQiVCWjRAAQjUAAiViWgA6DrZQiWiVAAjUQAAjTCWiVQBIhIBWglQBdgpBtAAQBvABBcAoQBWAlBIBIQCWCVAADTQAADUiWCVQiVCWjUAAQjTAAiViWg");
	this.shape_28.setTransform(251.4,213.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#0033FF").s().p("APhXSQiViVAAjUQAAjTCViWQBIhHBXgmQBdgnBtAAQBuAABdAnQBWAmBIBHQCVCWAADTQAADUiVCVQiVCWjUAAQjTAAiWiWgAmAXSQiViVAAjUQAAjTCViWQBIhHBWgmQBdgnBuAAQBrAABdAnQBWAmBIBHQCWCWAADTQAADUiWCVQiVCWjRAAQjUAAiViWgA6yXSQiViVAAjUQAAjTCViWQBIhHBWgmQBdgnBuAAQBtAABdAnQBWAmBIBHQCWCWAADTQAADUiWCVQiVCWjTAAQjUAAiViWgAPhFyQiViVAAjTQAAjSCViVQBIhJBXgkQBdgoBtgBQBuABBdAoQBWAkBIBJQCVCVAADSQAADTiVCVQiVCWjUAAQjTAAiWiWgAmAFyQiViVAAjTQAAjSCViVQBIhJBWgkQBdgoBugBQBrABBdAoQBWAkBIBJQCWCVAADSQAADTiWCVQiVCWjRAAQjUAAiViWgA6yFyQiViVAAjTQAAjSCViVQBIhJBWgkQBdgoBugBQBtABBdAoQBWAkBIBJQCWCVAADSQAADTiWCVQiVCWjTAAQjUAAiViWgAPhsAQiViVAAjUQAAjTCViWQBIhHBXgmQBdgnBtAAQBuAABdAnQBWAmBIBHQCVCWAADTQAADUiVCVQiVCWjUAAQjTAAiWiWgAmAsAQiViVAAjUQAAjTCViWQBIhHBWgmQBdgnBuAAQBrAABdAnQBWAmBIBHQCWCWAADTQAADUiWCVQiVCWjRAAQjUAAiViWgA6ysAQiViVAAjUQAAjTCViWQBIhHBWgmQBdgnBuAAQBtAABdAnQBWAmBIBHQCWCWAADTQAADUiWCVQiVCWjTAAQjUAAiViWg");
	this.shape_29.setTransform(251.5,214);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[{t:this.shape_9}]},1).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).to({state:[{t:this.shape_20}]},1).to({state:[{t:this.shape_21}]},1).to({state:[{t:this.shape_22}]},1).to({state:[{t:this.shape_23}]},1).to({state:[{t:this.shape_24}]},1).to({state:[{t:this.shape_25}]},1).to({state:[{t:this.shape_26}]},1).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(473,335,102,102);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;